name: MoneyTicket
version: @version@
author: testusuke
main: net.testusuke.moneyticket.MoneyTicket
commands:
  mt:
    description: If you want to create MoneyTicket,you need permission'moneyticket.create'
  moneyticket: